### ISSUE TITLE
Not launched in your country

### ISSUE THREAD

**Issue by MarkoShiva** [keshavbhatt/olivia#77] opened 2020-01-11 22:25 UTC
I get error for recommendation and home age with not launched in your country so I need to search for option which is only available when click on youtube to change country.
App can be done better. Visual appeal is nice but functionality is needed too.

**Comment by keshavbhatt** [comment] 2020-01-12 00:20
which country you are trying olivia from, sorry for inconvenience :(

**Comment by MarkoShiva** [comment] 2020-01-12 00:53
I'm trying from Serbia. Unfortunately not sure what is the issue there. We actually have Youtube Music here I mean I am using it on android mobile as well as using some unofficial apps for youtube music for desktop. 
However I get that error when starting the app. If I change country to some other like United Kingdom for example I get those lists working.

Also to mention there is a need to click refresh on failed load of data for genres and new releases. I guess that is related to not being able to get the data without changing the country setting which is totally fine with me as I don't listen the music from Serbia. 

Anyway good luck with the project app looks really pretty. 
Any chance that you will add spotify in future? I mean spotify premium at least?

**Comment by MarkoShiva** [comment] 2020-01-12 01:12
If you need help I would be willing to try to help you make nice native C++ app for linux that will work as good cloud player. 
There are few things in UI that I noticed that are problem.
For example its pretty hard to actually switch to video and play video which actually plays in mpv which is used as backend app for play here which is ok. Maybe not the best solution as there is a native QT widget that can work with video files. 
One of the problems is long buffering its probably related to the fact that you are not prefetching songs
from queue. 
Also there is a problem when switching to video audio player do not stop I think that you should issue pause to player when video is played from app but that can be reworked.
Good luck.

**Comment by keshavbhatt** [comment] 2020-01-12 04:12
hey thanks for pointing out these issues, am aware of few of them. issue with using Qtmultimedia module is that, am using qt5.5.1 which has webkit module (lighter & minimal than webengine) the problem is these two modules are not working together as they are compiled with different version of gstreamer libraries, http streaming doesn't work in this situation. https://bugzilla.redhat.com/show_bug.cgi?id=1149885 .
Video and audio switching problem can be fixed with existing implementation though. mpv is good as backend as it can play almost anything.

**Comment by keshavbhatt** [comment] 2020-01-12 04:15
the issue not launched in your country(Serbia) i will fix soon, by making it fallback to some other country if this case exists.
this is due to the fact that spotify is not launched there or maybe API doesn't work there.

**Comment by keshavbhatt** [comment] 2020-01-12 04:17
@MarkoShiva yes i would like to work with you for sure :)

**Comment by keshavbhatt** [comment] 2020-01-14 12:17
This issue has been fixed from server side changes. 
Now if someone from unlaunched country requests data Olivia will make US as fallback country.
Thanks for reporting.

**Closed by keshavbhatt** 2020-01-14 12:17 UTC

**Comment by MarkoShiva** [comment] 2020-01-14 22:50
Thanks I can confirm that on a fresh install it fallback to US.
